[project]
name = "housing-prices-statistics"
version = "0.1.0"
description = "extract data from CSV and create diagrams, made for GDE university project"
requires-python = ">=3.9"
dependencies = [
    "numpy",
    "matplotlib",
    "colorama",
]